FROM scratch
ENV PATH {{path}}
ADD {{rootfs}} /

# This is to support installing packages (and thus, updates) as a
# non-root Supervisor
RUN mkdir -p /home/hab_non_root && chmod -R g=u /home/hab_non_root
ENV HOME=/home/hab_non_root

EXPOSE 9631 {{exposes}}
ENTRYPOINT ["/init.sh"]
CMD ["start", "{{primary_svc_ident}}"]
